# Generated by Django 4.2.8 on 2023-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('group', models.CharField(max_length=100, verbose_name='группа')),
                ('goal', models.TextField(verbose_name='зачем нужна?')),
                ('character', models.TextField(verbose_name='характер')),
                ('comment', models.TextField(verbose_name='комментарий автора')),
                ('main_image', models.ImageField(upload_to='images', verbose_name='основное изображение')),
                ('image1', models.ImageField(upload_to='images', verbose_name='изображение для карусели 1')),
                ('image2', models.ImageField(upload_to='images', verbose_name='изображение для карусели 2')),
                ('image3', models.ImageField(upload_to='images', verbose_name='изображение для карусели 3')),
            ],
        ),
    ]
