# Generated by Django 4.2.8 on 2023-12-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='group',
        ),
    ]
